trigger:
- main # Automatically triggers on updates to the 'main' branch

pool:
  name: gittoacr # Specify the agent pool

variables:
  - group: pipelines connector # Reference the first variable group
  - group: gittoacr

steps:
# Step 1: Checkout the GitHub repository
- checkout: self
  displayName: 'Clone GitHub Repository'

# Step 2: Login to Azure Container Registry (ACR) using Azure CLI
- script: |
    echo Logging in to Azure Container Registry using Azure CLI...
    az acr login --name $(acrLoginServer)
    echo Logged into ACR successfully!
  displayName: 'Login to ACR via Azure CLI'

# Step 3: Build the project
- script: |
    echo Building the project...
    REM Add specific commands for your project build below
    echo Project build completed successfully!
  displayName: 'Build Project'

# Step 4: Build Docker Image
- script: |
    echo Building Docker image...
    docker build -t $(acrLoginServer).azurecr.io/$(acrRepository):$(dockerImageTag) .
    echo Docker image built successfully!
  displayName: 'Build Docker Image via CLI'

# Step 5: Push Docker Image to ACR
- script: |
    echo Pushing Docker image to ACR...
    docker push $(acrLoginServer).azurecr.io/$(acrRepository):$(dockerImageTag)
    echo Docker image pushed successfully!
  displayName: 'Push Docker Image via CLI'

# Step 6: Confirm the Docker image was pushed successfully
- script: |
    echo Docker image successfully pushed to ACR!
    echo Image URL: $(acrLoginServer).azurecr.io/$(acrRepository):$(dockerImageTag)
  displayName: 'Confirm Docker Image Push'

# Step 7: Trigger the Second Pipeline
- script: |
    echo Triggering second pipeline using Azure DevOps REST API...
    curl -u "$(AZURE_DEVOPS_USERNAME):$(AZURE_DEVOPS_PAT)" `
         -X POST `
         -H "Content-Type: application/json" `
         -d '{"resources": {"repositories": {"self": {"refName": "refs/heads/main"}}}}' `
         https://dev.azure.com/$(Organization)/ACR%20to%20Webapp/_apis/pipelines/$(pipelineId)/runs?api-version=7.1-preview
    echo Second pipeline triggered successfully!
  displayName: 'Trigger Second Pipeline'